"""Cria tabelas de gerenciamento administrativo

Revision ID: 094e7914cda9
Revises: 35bb485b7eb1
Create Date: 2026-01-18 11:21:19.908672

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '094e7914cda9'
down_revision: Union[str, Sequence[str], None] = '35bb485b7eb1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE SCHEMA IF NOT EXISTS tenant")
    op.create_table('entradas',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('data_entrada', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('nome', sa.String(), nullable=True),
    sa.Column('fornecedor', sa.String(), nullable=True),
    sa.Column('quantidade', sa.Integer(), nullable=False),
    sa.Column('valor_unitario', sa.Integer(), nullable=False),
    sa.Column('preco_total', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='tenant'
    )
    op.create_table('materiais',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('codigo', sa.VARCHAR(length=10), nullable=False),
    sa.Column('fornecedor', sa.String(length=50), nullable=False),
    sa.Column('nome', sa.String(length=50), nullable=False),
    sa.Column('tipo', sa.String(length=50), nullable=False),
    sa.Column('valor_unitario', sa.Integer(), nullable=False),
    sa.Column('preco_total', sa.Integer(), nullable=False),
    sa.Column('quantidade', sa.Integer(), nullable=False),
    sa.Column('estoque', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo'),
    sa.UniqueConstraint('nome'),
    schema='tenant'
    )
    op.create_table('saidas',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('data_saida', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('nome', sa.String(), nullable=True),
    sa.Column('bloco', sa.String(), nullable=True),
    sa.Column('quantidade', sa.Integer(), nullable=False),
    sa.Column('valor_unitario', sa.Integer(), nullable=False),
    sa.Column('preco_total', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='tenant'
    )
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=50), nullable=False),
    sa.Column('sobrenome', sa.String(length=100), nullable=True),
    sa.Column('cargo', sa.String(length=50), server_default='user', nullable=False),
    sa.Column('email', sa.String(length=70), nullable=False),
    sa.Column('senha', sa.String(length=250), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    schema='tenant'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('usuarios', schema='tenant')
    op.drop_table('saidas', schema='tenant')
    op.drop_table('materiais', schema='tenant')
    op.drop_table('entradas', schema='tenant')
    # ### end Alembic commands ###
