"""Cria tabelas de gerenciamento administrativo

Revision ID: 0db905594f1b
Revises: 
Create Date: 2026-01-12 13:13:48.402229

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0db905594f1b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('EntradaAlmoxarifado',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('data_entrada', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('nome', sa.String(), nullable=True),
    sa.Column('fornecedor', sa.String(), nullable=True),
    sa.Column('quantidade', sa.Integer(), nullable=False),
    sa.Column('valor_unitario', sa.Integer(), nullable=False),
    sa.Column('preco_total', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('MateriaisAlmoxarifado',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('codigo', sa.VARCHAR(length=10), nullable=False),
    sa.Column('fornecedor', sa.String(length=50), nullable=False),
    sa.Column('nome', sa.String(length=50), nullable=False),
    sa.Column('tipo', sa.String(length=50), nullable=False),
    sa.Column('valor_unitario', sa.Integer(), nullable=False),
    sa.Column('preco_total', sa.Integer(), nullable=False),
    sa.Column('quantidade', sa.Integer(), nullable=False),
    sa.Column('estoque', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('SaidaAlmoxarifado',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('data_saida', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('nome', sa.String(), nullable=True),
    sa.Column('bloco', sa.String(), nullable=True),
    sa.Column('quantidade', sa.Integer(), nullable=False),
    sa.Column('valor_unitario', sa.Integer(), nullable=False),
    sa.Column('preco_total', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Usuarios',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=50), nullable=False),
    sa.Column('sobrenome', sa.String(length=100), nullable=True),
    sa.Column('cargo', sa.String(length=50), server_default='user', nullable=False),
    sa.Column('email', sa.String(length=70), nullable=False),
    sa.Column('senha', sa.String(length=250), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Usuarios')
    op.drop_table('SaidaAlmoxarifado')
    op.drop_table('MateriaisAlmoxarifado')
    op.drop_table('EntradaAlmoxarifado')
    # ### end Alembic commands ###
