"""Cria tabelas de gerenciamento administrativo

Revision ID: 1b8d1fbb0e39
Revises: cc532809a9e4
Create Date: 2026-01-24 16:49:45.363598

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1b8d1fbb0e39'
down_revision: Union[str, Sequence[str], None] = 'cc532809a9e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade():
    op.execute("CREATE SCHEMA IF NOT EXISTS tenant_default")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entradas',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('data_entrada', sa.Date(), server_default=sa.text('now()'), nullable=True),
    sa.Column('nome', sa.String(), nullable=True),
    sa.Column('fornecedor', sa.String(), nullable=True),
    sa.Column('quantidade', sa.Integer(), nullable=False),
    sa.Column('valor_unitario', sa.Integer(), nullable=False),
    sa.Column('preco_total', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_entradas')),
    schema='tenant_default'
    )
    op.create_table('materiais',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('codigo', sa.VARCHAR(length=10), nullable=False),
    sa.Column('fornecedor', sa.String(length=50), nullable=False),
    sa.Column('nome', sa.String(length=50), nullable=False),
    sa.Column('tipo', sa.String(length=50), nullable=False),
    sa.Column('valor_unitario', sa.Integer(), nullable=False),
    sa.Column('preco_total', sa.Integer(), nullable=False),
    sa.Column('quantidade', sa.Integer(), nullable=False),
    sa.Column('estoque', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_materiais')),
    sa.UniqueConstraint('codigo', name=op.f('uq_materiais_codigo')),
    sa.UniqueConstraint('nome', name=op.f('uq_materiais_nome')),
    schema='tenant_default'
    )
    op.create_table('saidas',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('data_saida', sa.Date(), server_default=sa.text('now()'), nullable=True),
    sa.Column('nome', sa.String(), nullable=True),
    sa.Column('bloco', sa.String(), nullable=True),
    sa.Column('quantidade', sa.Integer(), nullable=False),
    sa.Column('valor_unitario', sa.Integer(), nullable=False),
    sa.Column('preco_total', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_saidas')),
    schema='tenant_default'
    )
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_schema', sa.String(length=50), nullable=True),
    sa.Column('nome', sa.String(length=50), nullable=False),
    sa.Column('sobrenome', sa.String(length=100), nullable=True),
    sa.Column('cargo', sa.String(length=50), server_default='user', nullable=False),
    sa.Column('email', sa.String(length=70), nullable=False),
    sa.Column('senha', sa.String(length=250), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_usuarios')),
    sa.UniqueConstraint('email', name=op.f('uq_usuarios_email')),
    schema='tenant_default'
    )
    op.drop_table('usuarios', schema='usuarios')
    op.drop_table('entradas', schema='tenant')
    op.drop_table('saidas', schema='testes2')
    op.drop_table('entradas', schema='testes2')
    op.drop_table('saidas', schema='usuarios')
    op.drop_table('materiais', schema='testes2')
    op.drop_index(op.f('ix_shared_tenants_name'), table_name='tenants', schema='shared')
    op.drop_table('tenants', schema='shared')
    op.drop_table('materiais', schema='usuarios')
    op.drop_table('usuarios', schema='testes')
    op.drop_table('entradas', schema='usuarios')
    op.drop_table('usuarios', schema='tenant')
    op.drop_table('usuarios', schema='testes2')
    op.drop_table('entradas', schema='testes')
    op.drop_table('saidas', schema='tenant')
    op.drop_table('materiais', schema='testes')
    op.drop_table('saidas', schema='testes')
    op.drop_table('materiais', schema='tenant')
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('materiais',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('codigo', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('fornecedor', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('nome', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('tipo', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('valor_unitario', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('preco_total', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('quantidade', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('estoque', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('materiais_pkey')),
    sa.UniqueConstraint('codigo', name=op.f('materiais_codigo_key'), postgresql_include=[], postgresql_nulls_not_distinct=False),
    sa.UniqueConstraint('nome', name=op.f('materiais_nome_key'), postgresql_include=[], postgresql_nulls_not_distinct=False),
    schema='tenant'
    )
    op.create_table('saidas',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('data_saida', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('nome', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('bloco', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('quantidade', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('valor_unitario', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('preco_total', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('saidas_pkey')),
    schema='testes'
    )
    op.create_table('materiais',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('codigo', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('fornecedor', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('nome', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('tipo', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('valor_unitario', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('preco_total', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('quantidade', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('estoque', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('materiais_pkey')),
    sa.UniqueConstraint('codigo', name=op.f('materiais_codigo_key'), postgresql_include=[], postgresql_nulls_not_distinct=False),
    sa.UniqueConstraint('nome', name=op.f('materiais_nome_key'), postgresql_include=[], postgresql_nulls_not_distinct=False),
    schema='testes'
    )
    op.create_table('saidas',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('data_saida', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('nome', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('bloco', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('quantidade', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('valor_unitario', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('preco_total', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('saidas_pkey')),
    schema='tenant'
    )
    op.create_table('entradas',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('data_entrada', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('nome', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('fornecedor', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('quantidade', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('valor_unitario', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('preco_total', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('entradas_pkey')),
    schema='testes'
    )
    op.create_table('usuarios',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('tenant_schema', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('nome', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('sobrenome', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('cargo', sa.VARCHAR(length=50), server_default=sa.text("'user'::character varying"), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=70), autoincrement=False, nullable=False),
    sa.Column('senha', sa.VARCHAR(length=250), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_usuarios')),
    sa.UniqueConstraint('email', name=op.f('usuarios_email_key'), postgresql_include=[], postgresql_nulls_not_distinct=False),
    schema='testes2'
    )
    op.create_table('usuarios',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('tenant_schema', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('nome', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('sobrenome', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('cargo', sa.VARCHAR(length=50), server_default=sa.text("'user'::character varying"), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=70), autoincrement=False, nullable=False),
    sa.Column('senha', sa.VARCHAR(length=250), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('usuarios_pkey')),
    sa.UniqueConstraint('email', name=op.f('usuarios_email_key'), postgresql_include=[], postgresql_nulls_not_distinct=False),
    schema='tenant'
    )
    op.create_table('entradas',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('data_entrada', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('nome', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('fornecedor', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('quantidade', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('valor_unitario', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('preco_total', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('entradas_pkey')),
    schema='usuarios'
    )
    op.create_table('usuarios',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('tenant_schema', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('nome', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('sobrenome', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('cargo', sa.VARCHAR(length=50), server_default=sa.text("'user'::character varying"), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=70), autoincrement=False, nullable=False),
    sa.Column('senha', sa.VARCHAR(length=250), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('usuarios_pkey')),
    sa.UniqueConstraint('email', name=op.f('usuarios_email_key'), postgresql_include=[], postgresql_nulls_not_distinct=False),
    schema='testes'
    )
    op.create_table('materiais',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('codigo', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('fornecedor', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('nome', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('tipo', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('valor_unitario', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('preco_total', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('quantidade', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('estoque', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('materiais_pkey')),
    sa.UniqueConstraint('codigo', name=op.f('materiais_codigo_key'), postgresql_include=[], postgresql_nulls_not_distinct=False),
    sa.UniqueConstraint('nome', name=op.f('materiais_nome_key'), postgresql_include=[], postgresql_nulls_not_distinct=False),
    schema='usuarios'
    )
    op.create_table('tenants',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=256), autoincrement=False, nullable=False),
    sa.Column('schema', sa.VARCHAR(length=256), autoincrement=False, nullable=False),
    sa.Column('host', sa.VARCHAR(length=256), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('tenants_pkey')),
    sa.UniqueConstraint('host', name=op.f('tenants_host_key'), postgresql_include=[], postgresql_nulls_not_distinct=False),
    sa.UniqueConstraint('schema', name=op.f('tenants_schema_key'), postgresql_include=[], postgresql_nulls_not_distinct=False),
    schema='shared'
    )
    op.create_index(op.f('ix_shared_tenants_name'), 'tenants', ['name'], unique=True, schema='shared')
    op.create_table('materiais',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('codigo', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('fornecedor', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('nome', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('tipo', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('valor_unitario', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('preco_total', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('quantidade', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('estoque', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_materiais')),
    sa.UniqueConstraint('codigo', name=op.f('materiais_codigo_key'), postgresql_include=[], postgresql_nulls_not_distinct=False),
    sa.UniqueConstraint('nome', name=op.f('materiais_nome_key'), postgresql_include=[], postgresql_nulls_not_distinct=False),
    schema='testes2'
    )
    op.create_table('saidas',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('data_saida', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('nome', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('bloco', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('quantidade', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('valor_unitario', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('preco_total', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('saidas_pkey')),
    schema='usuarios'
    )
    op.create_table('entradas',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('data_entrada', sa.DATE(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('nome', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('fornecedor', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('quantidade', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('valor_unitario', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('preco_total', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_entradas')),
    schema='testes2'
    )
    op.create_table('saidas',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('data_saida', sa.DATE(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('nome', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('bloco', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('quantidade', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('valor_unitario', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('preco_total', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_saidas')),
    schema='testes2'
    )
    op.create_table('entradas',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('data_entrada', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('nome', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('fornecedor', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('quantidade', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('valor_unitario', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('preco_total', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('entradas_pkey')),
    schema='tenant'
    )
    op.create_table('usuarios',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('tenant_schema', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('nome', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('sobrenome', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('cargo', sa.VARCHAR(length=50), server_default=sa.text("'user'::character varying"), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=70), autoincrement=False, nullable=False),
    sa.Column('senha', sa.VARCHAR(length=250), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('usuarios_pkey')),
    sa.UniqueConstraint('email', name=op.f('usuarios_email_key'), postgresql_include=[], postgresql_nulls_not_distinct=False),
    schema='usuarios'
    )
    op.drop_table('usuarios', schema='tenant_default')
    op.drop_table('saidas', schema='tenant_default')
    op.drop_table('materiais', schema='tenant_default')
    op.drop_table('entradas', schema='tenant_default')
    # ### end Alembic commands ###
