"""Cria tabelas de gerenciamento administrativo

Revision ID: 2d3c93aab903
Revises: 1b8d1fbb0e39
Create Date: 2026-01-24 16:59:24.735857

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2d3c93aab903'
down_revision: Union[str, Sequence[str], None] = '1b8d1fbb0e39'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entradas',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('data_entrada', sa.Date(), server_default=sa.text('now()'), nullable=True),
    sa.Column('nome', sa.String(), nullable=True),
    sa.Column('fornecedor', sa.String(), nullable=True),
    sa.Column('quantidade', sa.Integer(), nullable=False),
    sa.Column('valor_unitario', sa.Integer(), nullable=False),
    sa.Column('preco_total', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_entradas')),
    schema='tenant_default'
    )
    op.create_table('materiais',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('codigo', sa.VARCHAR(length=10), nullable=False),
    sa.Column('fornecedor', sa.String(length=50), nullable=False),
    sa.Column('nome', sa.String(length=50), nullable=False),
    sa.Column('tipo', sa.String(length=50), nullable=False),
    sa.Column('valor_unitario', sa.Integer(), nullable=False),
    sa.Column('preco_total', sa.Integer(), nullable=False),
    sa.Column('quantidade', sa.Integer(), nullable=False),
    sa.Column('estoque', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_materiais')),
    sa.UniqueConstraint('codigo', name=op.f('uq_materiais_codigo')),
    sa.UniqueConstraint('nome', name=op.f('uq_materiais_nome')),
    schema='tenant_default'
    )
    op.create_table('saidas',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('data_saida', sa.Date(), server_default=sa.text('now()'), nullable=True),
    sa.Column('nome', sa.String(), nullable=True),
    sa.Column('bloco', sa.String(), nullable=True),
    sa.Column('quantidade', sa.Integer(), nullable=False),
    sa.Column('valor_unitario', sa.Integer(), nullable=False),
    sa.Column('preco_total', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_saidas')),
    schema='tenant_default'
    )
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_schema', sa.String(length=50), nullable=True),
    sa.Column('nome', sa.String(length=50), nullable=False),
    sa.Column('sobrenome', sa.String(length=100), nullable=True),
    sa.Column('cargo', sa.String(length=50), server_default='user', nullable=False),
    sa.Column('email', sa.String(length=70), nullable=False),
    sa.Column('senha', sa.String(length=250), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_usuarios')),
    sa.UniqueConstraint('email', name=op.f('uq_usuarios_email')),
    schema='tenant_default'
    )
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('usuarios', schema='tenant_default')
    op.drop_table('saidas', schema='tenant_default')
    op.drop_table('materiais', schema='tenant_default')
    op.drop_table('entradas', schema='tenant_default')
    # ### end Alembic commands ###
