"""Cria tabelas de gerenciamento administrativo

Revision ID: 6ee0091cecff
Revises: b101296f7101
Create Date: 2026-01-17 11:12:35.200779

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6ee0091cecff'
down_revision: Union[str, Sequence[str], None] = 'b101296f7101'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'MateriaisAlmoxarifado', ['nome'])
    op.create_unique_constraint(None, 'MateriaisAlmoxarifado', ['codigo'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'MateriaisAlmoxarifado', type_='unique')
    op.drop_constraint(None, 'MateriaisAlmoxarifado', type_='unique')
    # ### end Alembic commands ###
