"""Cria tabelas de gerenciamento administrativo

Revision ID: b0fad52807ad
Revises: b805232d359f
Create Date: 2026-01-18 12:05:44.858083

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b0fad52807ad'
down_revision: Union[str, Sequence[str], None] = 'b805232d359f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE SCHEMA IF NOT EXISTS tenant")
    op.execute("""
    CREATE TABLE IF NOT EXISTS tenant.entradas (
        id SERIAL NOT NULL,
        data_entrada TIMESTAMP WITH TIME ZONE DEFAULT now(),
        nome VARCHAR,
        fornecedor VARCHAR,
        quantidade INTEGER NOT NULL,
        valor_unitario INTEGER NOT NULL,
        preco_total INTEGER,
        PRIMARY KEY (id)
    )
    """)
    op.execute("""
    CREATE TABLE IF NOT EXISTS tenant.materiais (
        id SERIAL NOT NULL,
        codigo VARCHAR(10) NOT NULL,
        fornecedor VARCHAR(50) NOT NULL,
        nome VARCHAR(50) NOT NULL,
        tipo VARCHAR(50) NOT NULL,
        valor_unitario INTEGER NOT NULL,
        preco_total INTEGER NOT NULL,
        quantidade INTEGER NOT NULL,
        estoque VARCHAR NOT NULL,
        PRIMARY KEY (id),
        UNIQUE (codigo),
        UNIQUE (nome)
    )
    """)
    op.execute("""
    CREATE TABLE IF NOT EXISTS tenant.saidas (
        id SERIAL NOT NULL,
        data_saida TIMESTAMP WITH TIME ZONE DEFAULT now(),
        nome VARCHAR,
        bloco VARCHAR,
        quantidade INTEGER NOT NULL,
        valor_unitario INTEGER NOT NULL,
        preco_total INTEGER,
        PRIMARY KEY (id)
    )
    """)
    op.execute("""
    CREATE TABLE IF NOT EXISTS tenant.usuarios (
        id SERIAL NOT NULL,
        nome VARCHAR(50) NOT NULL,
        sobrenome VARCHAR(100),
        cargo VARCHAR(50) DEFAULT 'user' NOT NULL,
        email VARCHAR(70) NOT NULL,
        senha VARCHAR(250) NOT NULL,
        PRIMARY KEY (id),
        UNIQUE (email)
    )
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('usuarios', schema='tenant')
    op.drop_table('saidas', schema='tenant')
    op.drop_table('materiais', schema='tenant')
    op.drop_table('entradas', schema='tenant')
    # ### end Alembic commands ###
